name: Deploy Application

on:
  push:
    branches:
      - main # Trigger workflow on push to the 'main' branch

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker
      uses: docker/setup-buildx-action@v2

    - name: Build Docker image
      run: docker-compose build

    - name: Deploy to EC2
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        EC2_PUBLIC_IP: ${{ secrets.EC2_PUBLIC_IP }}
      run: |
        ssh -o StrictHostKeyChecking=no -i ~/.ssh/"C:\Users\PC\Downloads\new_key.pem" ec2-user@$54.226.133.84 << 'EOF'
        cd todo-list-app
        docker-compose pull
        docker-compose up -d
        EOF
