name: Deploy Application

on:
  push:
    branches:
      - main

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker
      uses: docker/setup-buildx-action@v2

    - name: Build Docker image
      run: docker-compose build

    - name: Deploy to EC2
  run: |
    # Add deployment steps to your EC2 instance
    echo "Starting deployment"

    # Save the private key to a file
    echo "${{ secrets.EC2_SSH_KEY }}" > ec2_key.pem
    chmod 600 ec2_key.pem

    # Connect to the EC2 instance and deploy the app
    ssh -o StrictHostKeyChecking=no -i ec2_key.pem ec2-user@<3.104.119.54> << 'EOF'
      # Navigate to the application directory
      cd /path/to/application

      # Pull the latest changes (if the repo is already cloned)
      git pull origin main

      # Rebuild and restart the Docker containers
      docker-compose down
      docker-compose up -d
    EOF

    # Clean up
    rm ec2_key.pem

